# Generated by Django 5.0.14 on 2026-05-24 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopkeeper',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shopkeepers', to='shops.branch'),
        ),
        migrations.AddField(
            model_name='shopkeeper',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopkeepers', to=settings.AUTH_USER_MODEL),
        ),
    ]
