version: '3.8'

services:
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    networks:
      - duka-network

  redis:
    image: redis:7
    networks:
      - duka-network

  web:
    build: .
    volumes:
      - .:/app
      - staticfiles:/app/staticfiles
      - mediafiles:/app/mediafiles
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=true
    depends_on:
      - db
      - redis
    expose:
      - "8000"
    networks:
      - duka-network

  worker:
    build: .
    command: celery -A config worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      - RUN_MIGRATIONS=false
    depends_on:
      - db
      - redis
    networks:
      - duka-network

volumes:
  postgres_data:
    name: duka_postgres_data
  staticfiles:
    name: duka_staticfiles
  mediafiles:
    name: duka_mediafiles

networks:
  duka-network:
    name: duka-network
