# Generated by Django 5.0.14 on 2026-05-24 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MpesaConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('PAYBILL', 'Paybill'), ('TILL', 'Buy Goods (Till)'), ('POCHI', 'Pochi la Biashara')], max_length=20)),
                ('business_number', models.CharField(help_text='Paybill or Till Number', max_length=20)),
                ('account_number', models.CharField(blank=True, help_text='Required for Paybill', max_length=50)),
                ('phone_number', models.CharField(blank=True, help_text='Required for Pochi', max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_configs', to='shops.branch')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mpesa_configs', to='shops.shop')),
            ],
        ),
    ]
